<?php

namespace app\validation;
/**
 * Created by PhpStorm.
 * User: toplink_php1
 * Date: 2018/7/10
 * Time: 10:54
 */
class GCreate extends \pms\Validation
{
    protected function initialize()
    {
        $this->add_callback('server', [
            'message' => 'server',
            'callback' => function ($data) {
                return is_string($data['server']);
            }
        ]);
        $this->add_callback('tx_name', [
            'message' => 'server',
            'callback' => function ($data) {
                return is_string($data['tx_name']);
            }
        ]);
        $this->add_callback('tx_data', [
            'message' => 'server',
            'callback' => function ($data) {
                return is_array($data['tx_data']);
            }
        ]);

        return parent::initialize(); // TODO: Change the autogenerated stub
    }

}